# Generated by Django 4.0.5 on 2022-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mediatype',
            field=models.IntegerField(choices=[(0, 'text'), (1, 'image'), (2, 'video'), (3, 'audio'), (4, 'document'), (5, 'location')], default=0),
        ),
    ]
